# cargo-deny configuration for sonido.
# The project itself is AGPL-3.0-or-later, but that isn't listed in [licenses.allow]
# because the allow list covers *dependency* licenses, not the project's own license.

[advisories]
vulnerability = "deny"
unmaintained = "warn"

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib"]
