//! DSP measurement report — proves the effects are *measured*, not just present.
//!
//! Drives flagship kernels with test signals and runs the output back through the
//! `sonido-analysis` FFT / THD / RT60 tooling, emitting a reproducible report
//! (`docs/DSP_MEASUREMENTS.md`) and an SVG harmonic-spectrum plot
//! (`docs/img/distortion-spectrum.svg`).
//!
//! Run from the workspace root:
//!     cargo run --release --example dsp_report -p sonido-effects
//!
//! Everything here is deterministic: same inputs, same numbers, every run.

use sonido_analysis::{ThdAnalyzer, Window, estimate_rt60, generate_test_tone, magnitude_spectrum};
use sonido_core::kernel::DspKernel;
use sonido_effects::kernels::{DistortionKernel, DistortionParams, ReverbKernel, ReverbParams};
use std::fmt::Write as _;
use std::fs;

const SR: f32 = 48_000.0;
const FFT: usize = 16_384;

/// Push a mono tone through a distortion kernel; return the (left) output.
fn drive_tone(params: &DistortionParams, tone: &[f32]) -> Vec<f32> {
    let mut k = DistortionKernel::new(SR);
    tone.iter()
        .map(|&s| k.process_stereo(s, s, params).0)
        .collect()
}

fn main() {
    let mut md = String::new();
    md.push_str("# DSP Measurements\n\n");
    md.push_str(
        "Reproducible measurements of flagship kernels, generated by\n\
         `cargo run --release --example dsp_report -p sonido-effects`. Signals are\n\
         analysed with the in-repo `sonido-analysis` FFT/THD/RT60 tooling — no external\n\
         tools, no hand-tuned numbers.\n\n",
    );
    writeln!(
        md,
        "Test conditions: {SR:.0} Hz sample rate, {FFT}-point FFT, Blackman–Harris window.\n"
    )
    .unwrap();

    // ── 1. THD vs drive (1 kHz fundamental) ──────────────────────────────────
    let tone = generate_test_tone(SR, 1000.0, FFT as f32 / SR, 0.5);
    let analyzer = ThdAnalyzer::new(SR, FFT);

    md.push_str("## Distortion — THD vs drive (1 kHz)\n\n");
    md.push_str("| Drive (dB) | THD (%) | THD (dB) | THD+N (%) |\n");
    md.push_str("|-----------:|--------:|---------:|----------:|\n");
    for knob in [0.25_f32, 0.5, 0.75, 1.0] {
        // from_knobs(drive, tone, output, shape, mix, dynamics) — normalized 0..1.
        let params = DistortionParams::from_knobs(knob, 0.5, 0.5, 0.0, 1.0, 0.0);
        let out = drive_tone(&params, &tone);
        let r = analyzer.analyze(&out, 1000.0);
        writeln!(
            md,
            "| {:>10.0} | {:>7.2} | {:>8.1} | {:>9.2} |",
            knob * 40.0,
            r.thd_ratio * 100.0,
            r.thd_db,
            r.thd_n_ratio * 100.0,
        )
        .unwrap();
    }
    md.push('\n');

    // ── 2. Harmonic structure at a fixed setting ─────────────────────────────
    let params = DistortionParams::from_knobs(0.75, 0.5, 0.5, 0.0, 1.0, 0.0);
    let out = drive_tone(&params, &tone);
    let r = analyzer.analyze(&out, 1000.0);
    let fund = r.harmonics.first().copied().unwrap_or(1.0).max(1e-12);

    md.push_str("## Distortion — harmonic structure (30 dB drive, 1 kHz)\n\n");
    md.push_str("Amplitude of each harmonic relative to the fundamental:\n\n");
    md.push_str("| Harmonic | Freq (Hz) | Level (dB) |\n");
    md.push_str("|---------:|----------:|-----------:|\n");
    for (i, &h) in r.harmonics.iter().enumerate().take(8) {
        let rel_db = 20.0 * (h / fund).max(1e-12).log10();
        writeln!(
            md,
            "| {:>8} | {:>9.0} | {:>10.1} |",
            i + 1,
            1000.0 * (i as f32 + 1.0),
            rel_db,
        )
        .unwrap();
    }
    md.push_str(
        "\nKernels run at base rate here; the desktop/plugin path wraps each kernel in\n\
         `Oversampled<N>` (`crates/sonido-core/src/oversample.rs`, windowed-sinc up/downsampling)\n\
         to keep these harmonics from aliasing back into the audible band.\n\n",
    );

    // ── 3. Reverb decay (RT60 from impulse response) ─────────────────────────
    let rev_params = ReverbParams::from_knobs(0.7, 0.85, 0.3, 0.0, 1.0, 0.5, 0.5, 0.5);
    let mut reverb = ReverbKernel::new(SR);
    let ir_len = (SR * 3.0) as usize;
    let mut ir = Vec::with_capacity(ir_len);
    for i in 0..ir_len {
        let x = if i == 0 { 1.0 } else { 0.0 };
        ir.push(reverb.process_stereo(x, x, &rev_params).0);
    }

    md.push_str("## Reverb — measured decay (Schroeder RT60)\n\n");
    if let Some(rt) = estimate_rt60(&ir, SR) {
        md.push_str("| Metric | Value (s) |\n|--------|----------:|\n");
        writeln!(md, "| RT60 | {:.2} |", rt.rt60_seconds).unwrap();
        writeln!(md, "| EDT (early decay) | {:.2} |", rt.edt_seconds).unwrap();
        writeln!(md, "| T30 | {:.2} |", rt.t30_seconds).unwrap();
        writeln!(md, "| Fit correlation | {:.3} |", rt.correlation).unwrap();
        md.push('\n');
    } else {
        md.push_str("_RT60 estimation returned no result for this setting._\n\n");
    }

    // ── 4. SVG harmonic-spectrum plot ────────────────────────────────────────
    let spectrum = magnitude_spectrum(&out, FFT, Window::Hann);
    let svg = spectrum_svg(&spectrum, SR, 8_000.0);
    fs::create_dir_all("docs/img").expect("create docs/img");
    fs::write("docs/img/distortion-spectrum.svg", svg).expect("write svg");
    md.push_str("## Distortion — output spectrum\n\n");
    md.push_str("![Distortion spectrum](img/distortion-spectrum.svg)\n\n");
    md.push_str(
        "*1 kHz fundamental at 30 dB drive; harmonic series visible at integer multiples.*\n",
    );

    fs::write("docs/DSP_MEASUREMENTS.md", &md).expect("write report");
    print!("{md}");
    eprintln!("\nwrote docs/DSP_MEASUREMENTS.md and docs/img/distortion-spectrum.svg");
}

/// Hand-rolled SVG log-magnitude spectrum plot (no plotting deps).
fn spectrum_svg(spectrum: &[f32], sample_rate: f32, max_freq: f32) -> String {
    const W: f32 = 900.0;
    const H: f32 = 360.0;
    const ML: f32 = 56.0; // left margin
    const MR: f32 = 16.0;
    const MT: f32 = 16.0;
    const MB: f32 = 40.0;
    let plot_w = W - ML - MR;
    let plot_h = H - MT - MB;
    let bin_hz = sample_rate / (spectrum.len() as f32 * 2.0);
    let db_min = -80.0_f32;
    let db_max = 0.0_f32;

    // Normalise to the peak so the plot is amplitude-independent.
    let peak = spectrum.iter().cloned().fold(1e-12_f32, f32::max);

    let x_of = |f: f32| ML + (f / max_freq).clamp(0.0, 1.0) * plot_w;
    let y_of = |db: f32| MT + (1.0 - ((db - db_min) / (db_max - db_min)).clamp(0.0, 1.0)) * plot_h;

    let mut pts = String::new();
    for (i, &m) in spectrum.iter().enumerate() {
        let f = i as f32 * bin_hz;
        if f > max_freq {
            break;
        }
        let db = 20.0 * (m / peak).max(1e-12).log10();
        let _ = write!(pts, "{:.1},{:.1} ", x_of(f), y_of(db));
    }

    let mut s = String::new();
    let _ = write!(
        s,
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="{W:.0}" height="{H:.0}" viewBox="0 0 {W:.0} {H:.0}" font-family="monospace" font-size="11">
<rect width="{W:.0}" height="{H:.0}" fill="#0f1117"/>
"##
    );
    // Horizontal gridlines / dB labels.
    for db in [-80, -60, -40, -20, 0] {
        let y = y_of(db as f32);
        let _ = write!(
            s,
            r##"<line x1="{ML:.0}" y1="{y:.1}" x2="{:.0}" y2="{y:.1}" stroke="#262b36"/><text x="{:.0}" y="{:.1}" fill="#7d8694" text-anchor="end">{db} dB</text>"##,
            W - MR,
            ML - 6.0,
            y + 3.0,
        );
    }
    // Vertical gridlines / freq labels.
    for khz in 0..=(max_freq as i32 / 1000) {
        let f = khz as f32 * 1000.0;
        let x = x_of(f);
        let _ = write!(
            s,
            r##"<line x1="{x:.1}" y1="{MT:.0}" x2="{x:.1}" y2="{:.1}" stroke="#262b36"/><text x="{x:.1}" y="{:.1}" fill="#7d8694" text-anchor="middle">{khz}k</text>"##,
            H - MB,
            H - MB + 16.0,
        );
    }
    let _ = write!(
        s,
        r##"<polyline points="{pts}" fill="none" stroke="#4fd1c5" stroke-width="1.2"/></svg>"##
    );
    s
}
